#pragma once


enum
{
	MAIN_ID = 0,
	MULTICAST_IP,
	BUTTON_ID,
};

#define COMTROL_INTERVAL_X					10
#define COMTROL_INTERVAL_Y					20

#define COMMON_CONTROL_WIDTH				120
#define COMMON_CONTROL_HEIGH				20

#define MAIN_WINDOW_WIDTH					850
#define MAIN_WINDOW_HEIGH					450


#define STATIC_LAB_MULTICAST_IP_X			30
#define STATIC_LAB_MULTICAST_IP_Y			25
#define STATIC_LAB_MULTICAST_IP_WIDTH		(COMMON_CONTROL_WIDTH)
#define STATIC_LAB_MUMTICAST_IP_HEIGH		(COMMON_CONTROL_HEIGH)
#define	STATIC_LAB_MULTICAST_IP_STYLE		(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_FLAT)

#define EDIT_MULTICAST_IP_X					(STATIC_LAB_MULTICAST_IP_X + STATIC_LAB_MULTICAST_IP_WIDTH + COMTROL_INTERVAL_X)
#define EDIT_MULTICAST_IP_Y					STATIC_LAB_MULTICAST_IP_Y
#define EDIT_MULTICAST_IP_WIDTH				(COMMON_CONTROL_WIDTH)
#define EDIT_MUMTICAST_IP_HEIGH				(COMMON_CONTROL_HEIGH)
#define EDIT_MULTICAST_IP_STYLE				(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_FLAT)

#define STATIC_LAB_NETCARD_SELECT_X			(STATIC_LAB_MULTICAST_IP_X)
#define STATIC_LAB_NETCARD_SELECT_Y			(STATIC_LAB_MULTICAST_IP_Y + STATIC_LAB_MUMTICAST_IP_HEIGH + COMTROL_INTERVAL_Y)
#define STATIC_LAB_NETCARD_SELECT_WIDTH		(COMMON_CONTROL_WIDTH)
#define STATIC_LAB_NETCARD_SELECT_HEIGH		(COMMON_CONTROL_HEIGH)
#define	STATIC_LAB_NETCARD_SELECT_STYLE		(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_FLAT)

#define COMBOBOX_NETCARD_SELECT_X			(STATIC_LAB_NETCARD_SELECT_X +  STATIC_LAB_NETCARD_SELECT_WIDTH + COMTROL_INTERVAL_X)
#define COMBOBOX_NETCARD_SELECT_Y			(STATIC_LAB_NETCARD_SELECT_Y)
#define COMBOBOX_NETCARD_SELECT_WIDTH		(COMMON_CONTROL_WIDTH)
#define COMBOBOX_NETCARD_SELECT_HEIGH		(COMMON_CONTROL_HEIGH)
#define COMBOBOX_NETCARD_SELECT_STYLE		(CBS_DROPDOWN | CBS_HASSTRINGS | WS_CHILD | WS_OVERLAPPED | WS_VISIBLE)

#define STATIC_LAB_INTERVAL_SELECT_X		(STATIC_LAB_MULTICAST_IP_X)
#define STATIC_LAB_INTERVAL_SELECT_Y		(COMBOBOX_NETCARD_SELECT_Y + COMBOBOX_NETCARD_SELECT_HEIGH + COMTROL_INTERVAL_Y)
#define STATIC_LAB_INTERVAL_SELECT_WIDTH	(COMMON_CONTROL_WIDTH)
#define STATIC_LAB_INTERVAL_SELECT_HEIGH	(COMMON_CONTROL_HEIGH)
#define	STATIC_LAB_INTERVAL_SELECT_STYLE	(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_RIGHT)

#define COMBOBOX_INTERVAL_SELECT_X			(STATIC_LAB_INTERVAL_SELECT_X +  STATIC_LAB_INTERVAL_SELECT_WIDTH + COMTROL_INTERVAL_X)
#define COMBOBOX_INTERVAL_SELECT_Y			(STATIC_LAB_INTERVAL_SELECT_Y)
#define COMBOBOX_INTERVAL_SELECT_WIDTH		(COMMON_CONTROL_WIDTH)
#define COMBOBOX_INTERVAL_SELECT_HEIGH		(COMMON_CONTROL_HEIGH)
#define COMBOBOX_INTERVAL_SELECT_STYLE		(CBS_DROPDOWN | CBS_HASSTRINGS | WS_CHILD | WS_OVERLAPPED | WS_VISIBLE)

#define EDIT_IMAGE_SELECT_X					(STATIC_LAB_MULTICAST_IP_X)
#define EDIT_IMAGE_SELECT_Y					(STATIC_LAB_INTERVAL_SELECT_Y + STATIC_LAB_INTERVAL_SELECT_HEIGH + 20 + COMTROL_INTERVAL_Y)
#define EDIT_IMAGE_SELECT_WIDTH				(COMMON_CONTROL_WIDTH * 3 + COMTROL_INTERVAL_X * 2)
#define EDIT_IMAGE_SELECT_HEIGH				(COMMON_CONTROL_HEIGH)
#define	EDIT_IMAGE_SELECT_STYLE				(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_RIGHT)

#define BUTTON_IMAGE_SELECT_X				(EDIT_IMAGE_SELECT_X +  EDIT_IMAGE_SELECT_WIDTH + COMTROL_INTERVAL_X)
#define BUTTON_IMAGE_SELECT_Y				(EDIT_IMAGE_SELECT_Y)
#define BUTTON_IMAGE_SELECT_WIDTH			(COMMON_CONTROL_WIDTH)
#define BUTTON_IMAGE_SELECT_HEIGH			(COMMON_CONTROL_HEIGH)
#define BUTTON_IMAGE_SELECT_STYLE			(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_FLAT)

#define STATIC_LAB_IMAGE_CRC_X				(EDIT_IMAGE_SELECT_X)
#define STATIC_LAB_IMAGE_CRC_Y				(EDIT_IMAGE_SELECT_Y + EDIT_IMAGE_SELECT_HEIGH + COMTROL_INTERVAL_Y)
#define STATIC_LAB_IMAGE_CRC_WIDTH			(COMMON_CONTROL_WIDTH)
#define STATIC_LAB_IMAGE_CRC_HEIGH			(COMMON_CONTROL_HEIGH)
#define	STATIC_LAB_IMAGE_CRC_STYLE			(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_RIGHT)

#define EDIT_IMAGE_CRC_X					(STATIC_LAB_IMAGE_CRC_X +  STATIC_LAB_IMAGE_CRC_WIDTH + COMTROL_INTERVAL_X)
#define EDIT_IMAGE_CRC_Y					(STATIC_LAB_IMAGE_CRC_Y)
#define EDIT_IMAGE_CRC_WIDTH				(COMMON_CONTROL_WIDTH)
#define EDIT_IMAGE_CRC_HEIGH				(COMMON_CONTROL_HEIGH)
#define EDIT_IMAGE_CRC_STYLE				(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_RIGHT)

#define STATIC_LAB_IMAGE_SIZE_X				(EDIT_IMAGE_CRC_X + EDIT_IMAGE_CRC_WIDTH + COMTROL_INTERVAL_X)
#define STATIC_LAB_IMAGE_SIZE_Y				(EDIT_IMAGE_CRC_Y)
#define STATIC_LAB_IMAGE_SIZE_WIDTH			(COMMON_CONTROL_WIDTH)
#define STATIC_LAB_IMAGE_SIZE_HEIGH			(COMMON_CONTROL_HEIGH)
#define	STATIC_LAB_IMAGE_SIZE_STYLE			(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_RIGHT)

#define EDIT_IMAGE_SIZE_X					(STATIC_LAB_IMAGE_SIZE_X +  STATIC_LAB_IMAGE_SIZE_WIDTH + COMTROL_INTERVAL_X)
#define EDIT_IMAGE_SIZE_Y					(STATIC_LAB_IMAGE_SIZE_Y)
#define EDIT_IMAGE_SIZE_WIDTH				(COMMON_CONTROL_WIDTH)
#define EDIT_IMAGE_SIZE_HEIGH				(COMMON_CONTROL_HEIGH)
#define EDIT_IMAGE_SIZE_STYLE				(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_RIGHT)

#define STATIC_LAB_IMAGE_NAME_X				(STATIC_LAB_IMAGE_CRC_X)
#define STATIC_LAB_IMAGE_NAME_Y				(STATIC_LAB_IMAGE_SIZE_Y + STATIC_LAB_IMAGE_SIZE_HEIGH + COMTROL_INTERVAL_Y)
#define STATIC_LAB_IMAGE_NAME_WIDTH			(COMMON_CONTROL_WIDTH)
#define STATIC_LAB_IMAGE_NAME_HEIGH			(COMMON_CONTROL_HEIGH)
#define	STATIC_LAB_IMAGE_NAME_STYLE			(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_RIGHT)

#define EDIT_IMAGE_NAME_X					(STATIC_LAB_IMAGE_NAME_X + STATIC_LAB_IMAGE_NAME_WIDTH + COMTROL_INTERVAL_X)
#define EDIT_IMAGE_NAME_Y					(STATIC_LAB_IMAGE_NAME_Y)
#define EDIT_IMAGE_NAME_WIDTH				(COMMON_CONTROL_WIDTH)
#define EDIT_IMAGE_NAME_HEIGH				(COMMON_CONTROL_HEIGH)
#define EDIT_IMAGE_NAME_STYLE				(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_RIGHT)

#define STATIC_LAB_SUB_FILE_COUNT_X			(EDIT_IMAGE_NAME_X + EDIT_IMAGE_NAME_WIDTH + COMTROL_INTERVAL_X)
#define STATIC_LAB_SUB_FILE_COUNT_Y			(EDIT_IMAGE_NAME_Y)
#define STATIC_LAB_SUB_FILE_COUNT_WIDTH		(COMMON_CONTROL_WIDTH)
#define STATIC_LAB_SUB_FILE_COUNT_HEIGH		(COMMON_CONTROL_HEIGH)
#define	STATIC_LAB_SUB_FILE_COUNT_STYLE		(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_RIGHT)

#define EDIT_SUB_FILE_COUNT_X				(STATIC_LAB_SUB_FILE_COUNT_X +  STATIC_LAB_SUB_FILE_COUNT_WIDTH + COMTROL_INTERVAL_X)
#define EDIT_SUB_FILE_COUNT_Y				(STATIC_LAB_SUB_FILE_COUNT_Y)
#define EDIT_SUB_FILE_COUNT_WIDTH			(COMMON_CONTROL_WIDTH)
#define EDIT_SUB_FILE_COUNT_HEIGH			(COMMON_CONTROL_HEIGH)
#define EDIT_SUB_FILE_COUNT_STYLE			(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_RIGHT)

#define PROGRESS_BAR_X						(STATIC_LAB_IMAGE_NAME_X)
#define PROGRESS_BAR_Y						(STATIC_LAB_IMAGE_NAME_Y + STATIC_LAB_IMAGE_NAME_HEIGH + COMTROL_INTERVAL_Y * 2)
#define PROGRESS_BAR_WIDTH					(MAIN_WINDOW_WIDTH - 70)
#define PROGRESS_BAR_HEIGH					(COMMON_CONTROL_HEIGH)
#define PROGRESS_BAR_STYLE					(WS_CHILD | WS_VISIBLE)

#define STATIC_TIMES_X						(PROGRESS_BAR_X)
#define STATIC_TIMES_Y						(PROGRESS_BAR_Y + PROGRESS_BAR_HEIGH + COMTROL_INTERVAL_Y * 2)
#define STATIC_TIMES_WIDTH					(COMMON_CONTROL_WIDTH)
#define STATIC_TIMES_HEIGH					(COMMON_CONTROL_HEIGH)
#define	STATIC_TIMES_STYLE					(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_RIGHT)

#define STATIC_PACKAGE_NO_X					(MAIN_WINDOW_WIDTH / 2  - COMMON_CONTROL_WIDTH )
#define STATIC_PACKAGE_NO_Y					(STATIC_TIMES_Y)
#define STATIC_PACKAGE_NO_WIDTH				(COMMON_CONTROL_WIDTH + 50)
#define STATIC_PACKAGE_NO_HEIGH				(COMMON_CONTROL_HEIGH)
#define	STATIC_PACKAGE_NO_STYLE				(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_RIGHT)

#define BUTTON_STOP_WIDTH					(COMMON_CONTROL_WIDTH / 2)
#define BUTTON_STOP_HEIGH					(COMMON_CONTROL_HEIGH)
#define BUTTON_STOP_Y						(STATIC_TIMES_Y)
#define BUTTON_STOP_X						(PROGRESS_BAR_X + PROGRESS_BAR_WIDTH - BUTTON_STOP_WIDTH)
#define	BUTTON_STOP_STYLE					(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_FLAT)

#define BUTTON_START_X						(BUTTON_STOP_X - BUTTON_STOP_WIDTH - COMTROL_INTERVAL_X * 2)
#define BUTTON_START_Y						(BUTTON_STOP_Y)
#define BUTTON_START_WIDTH					(COMMON_CONTROL_WIDTH / 2)
#define BUTTON_START_HEIGH					(COMMON_CONTROL_HEIGH)
#define BUTTON_START_STYLE					(WS_CHILD | WS_VISIBLE | WS_BORDER | BS_FLAT)

#define FILE_LIST_VIEW_WIDTH				(250)
#define FILE_LIST_VIEW_HEIGH				(250)
#define FILE_LIST_VIEW_X					(PROGRESS_BAR_X + PROGRESS_BAR_WIDTH - FILE_LIST_VIEW_WIDTH)
#define FILE_LIST_VIEW_Y					(STATIC_LAB_MULTICAST_IP_Y)

#define FILE_LIST_VIEW_STYLE				( WS_TABSTOP | WS_CHILD | WS_BORDER | WS_VISIBLE | LVS_AUTOARRANGE)



typedef struct myControl
{
	HWND hWnd;

	LPCWSTR dwExStyle;
	LPCWSTR lpClassName;
	DWORD dwStyle;
	int x;
	int y;
	int nWidth;
	int nHeigh;
	HWND hWndParent;
	HMENU hMenu;
	HINSTANCE hInstance;
	LPVOID lpParam;

	int (*InitHandler)(struct myControl* control);
	int (*MessagHeandler)(struct myControl* control, HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam);

}MyControl_t;